raw_video_directory: /tank/shared/2022/arrow_of_time/derivatives/stimuli/raw/flat_db/
cut_stimulus_video_directory: /tank/shared/2022/arrow_of_time/derivatives/stimuli/cut
rescaled_stimulus_video_directory: /tank/shared/2022/arrow_of_time/derivatives/stimuli/rescaled

preferred_n_jobs_info: 40
preferred_n_jobs_transcode: 8

desired_video_info: ['width', 'height', 'codec_name', 'bit_rate', 'nb_frames','pix_fmt', 'duration', 'r_frame_rate']
ffmpeg_settings:
    pix_fmt: yuv420p
    codec: libx264
    crf: 18
    preset: veryslow
    framerate: 24
    format: mp4
    size: "1920:1080"
    video_duration: 2.5
